# This file was generated by GoReleaser. DO NOT EDIT.
class Gbk2utf8 < Formula
  desc "GB2312/GBK/GB18030 与 UTF-8 的编码转换器"
  homepage "https://github.com/fluffos/gbk2utf8"
  version "1.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fluffos/gbk2utf8/releases/download/v1.0.2/gbk2utf8_v1.0.2_Darwin_x86_64.tar.gz"
    sha256 "1c8e673d26e2d11f07d2889d04d51954d5e94b36c0ed3528f35bb915f58ed21b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/fluffos/gbk2utf8/releases/download/v1.0.2/gbk2utf8_v1.0.2_Linux_x86_64.tar.gz"
      sha256 "0435a3c40024732923043f054e32b9b5f3cc23ee1d592c3ecf0fb456672cbc84"
    end
  end

  def install
    bin.install "gbk2utf8"
  end
end
