# This file was generated by GoReleaser. DO NOT EDIT.
class Gbk2utf8 < Formula
  desc "GB2312/GBK/GB18030 与 UTF-8 的编码转换器"
  homepage "https://github.com/fluffos/gbk2utf8"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fluffos/gbk2utf8/releases/download/v1.0.0/gbk2utf8_v1.0.0_Darwin_x86_64.tar.gz"
    sha256 "70b40f4615165b4dc2411a30b2053b95c7edad2fc5eb814e55e1cf17cc9bc093"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/fluffos/gbk2utf8/releases/download/v1.0.0/gbk2utf8_v1.0.0_Linux_x86_64.tar.gz"
      sha256 "222d0c25f01367088980a0f9f66a448ab2fa3a2716a5d977806ec201d0d098b0"
    end
  end

  def install
    bin.install "gbk2utf8"
  end
end
