# This file was generated by GoReleaser. DO NOT EDIT.
class GoMud < Formula
  desc "一个用 Go 语言开发的 MUD 客户端"
  homepage "https://github.com/mudclient/go-mud"
  version "0.6.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mudclient/go-mud/releases/download/v0.6.6/go-mud_v0.6.6_Darwin_x86_64.tar.gz"
    sha256 "074c56f155123a3cd948eb3913fdad75b74f6031bdf9ea2072c17270105a9351"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mudclient/go-mud/releases/download/v0.6.6/go-mud_v0.6.6_Linux_x86_64.tar.gz"
    sha256 "e08567cf471d987f02ba185597e09a5c1d4d7945a7f69f62015557fc28b94297"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/mudclient/go-mud/releases/download/v0.6.6/go-mud_v0.6.6_Linux_ARMv6.tar.gz"
    sha256 "a3a129c84b32576be083d0e8c15a0826b3ad66717f9d86eec816be4228f9b6b2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mudclient/go-mud/releases/download/v0.6.6/go-mud_v0.6.6_Linux_ARMv8.tar.gz"
    sha256 "b20539fe880b636bdc42ea8e364837ad59a7d240dd9d3f90874398db3df2cc2d"
  end

  def install
    bin.install "go-mud"
  end
end
